### ISSUE TITLE
Should be able to pass an option to share a different url

### ISSUE THREAD

**Issue by woodhull** [controlshift/facebook_share_widget_rails#5]
Currently, I have no idea what url is being sent to facebook. Is the URL being shared is the URL that the widget is on?

You should be able to share any arbitrary URL.

**Comment by woodhull** [comment]
I'm waiting to close this issue till I get the permissions working locally. I can't verify that it works inside facebook.

**Comment by seanhotw** [comment]
fixed and tested. can pass in any params for a facebook post request, not just the link.

http://developers.facebook.com/docs/reference/api/post/
